### ISSUE TITLE
simple color changing shader test works in master branch,  'pthreads are not available' with 0.11 

### ISSUE THREAD

**Issue by jojomickymack** [TannerRogalsky/love.js#57]
I made a simple test project which rotates an image while a shader modifies the green value - I was pleased to find that when compiling with the master branch that the shader performs as normal with love.js in the browser!
I also tested the same love project using 0.11 installed via npm and saw that while the image still could be seen rotating, instead of the shader being applied, it's just a bright pink/blue color.

In the console I see this error
Current environment does not support SharedArrayBuffer, pthreads are not available!

It's just interesting that pthreads are apparently available with the master version of love.js and not 0.11.

Tested in Firefox 57.0.4 on windows - I did see the same pink/blue thing in Chrome and Edge as well. I'd be happy to provide the project used for testing if you're trying to reproduce.

**Comment by TannerRogalsky** [comment]
The master branch of this repo was not compiled with threads enabled. It's one of the major differences with the new version that I've got threads enabled and working.

But you will require a browser with SharedArrayBuffers enabled. Your version of Firefox supports them but they are disabled by default because of a recent cybersecurity threat. https://www.mozilla.org/en-US/security/advisories/mfsa2018-01/

Nothing I can do about that, unfortunately. Time will, hopefully, stabilize these required features.
